(function () {

	'use strict';

	function ItzulpenFactory () {
		
		var itzulpenak = [
			{ castellano: "Portal", euskara: "Atari", level: 3},
			{ castellano: "Escribir", euskara: "Idatzi", level: 3},
			{ castellano: "Actividad", euskara: "Jarduera", level: 3},
			{ castellano: "Tarea", euskara: "Jarduera", level: 3},
			{ castellano: "Carga", euskara: "Zama", level: 3},
			{ castellano: "Atrevido", euskara: "Ausarta", level: 3},
			{ castellano: "Valiente", euskara: "Ausarta", level: 3},
			{ castellano: "Travieso", euskara: "Bihurri", level: 3},
			{ castellano: "Forma de ser", euskara: "Izaera", level: 3},
			{ castellano: "Carácter", euskara: "Izaera", level: 3},
			{ castellano: "Error", euskara: "Oker", level: 3},
			{ castellano: "Equivocación", euskara: "Oker", level: 3},
			{ castellano: "Bromista", euskara: "Txantxazale", level: 3},
			{ castellano: "Falsa impresión", euskara: "Uste oker", level: 3},
			{ castellano: "Creencia", euskara: "Uste", level: 3},
			{ castellano: "Opinión", euskara: "Uste", level: 3},
			{ castellano: "Idea", euskara: "Uste", level: 3},
			{ castellano: "Formal", euskara: "Zintzo", level: 3},
			{ castellano: "Honesto", euskara: "Zintzo", level: 3},
			{ castellano: "Característica", euskara: "Ezaugarri", level: 3},
			{ castellano: "Aptitud", euskara: "Gaitasun", level: 3},
			{ castellano: "Capacidad", euskara: "Gaitasun", level: 3},
			{ castellano: "Anuncio", euskara: "Iragarki", level: 3},
			{ castellano: "Disponible", euskara: "Eskuragarri", level: 3},
			{ castellano: "Alguien", euskara: "Norbait", level: 3},
			{ castellano: "Nota", euskara: "Ohar", level: 3},
			{ castellano: "Formación", euskara: "Prestakuntza", level: 3},
			{ castellano: "Preparación", euskara: "Prestakuntza", level: 3},
			{ castellano: "Canguro", euskara: "Umezain", level: 3},
			{ castellano: "Niñero", euskara: "Umezain", level: 3},
			{ castellano: "Alquilar", euskara: "Alokatu", level: 3},
			{ castellano: "Bellas artes", euskara: "Arte ederrak", level: 3},
			{ castellano: "Viajar", euskara: "Bidaiatu", level: 3},
			{ castellano: "Fácilmente", euskara: "Erraz", level: 3},
			{ castellano: "Fumador", euskara: "Erretzaile", level: 3},
			{ castellano: "Clase", euskara: "Ikasgela", level: 3},
			{ castellano: "Aula", euskara: "Ikasgela", level: 3},
			{ castellano: "Abrir", euskara: "Ireki", level: 3},
			{ castellano: "Periodismo", euskara: "Kazetaritza", level: 3},
			{ castellano: "Dormitorio", euskara: "Logela", level: 3},
			{ castellano: "Adaptarse", euskara: "Moldatu", level: 3},
			{ castellano: "Arreglarse", euskara: "Moldatu", level: 3},
			{ castellano: "Completar", euskara: "Osatu", level: 3},
			{ castellano: "Compañero de piso", euskara: "Pisukide", level: 3},
			{ castellano: "Psicología", euskara: "Psikologia", level: 3},
			{ castellano: "Vendedor", euskara: "Saltzaile", level: 3},
			{ castellano: "Turno", euskara: "Txanda", level: 3},
			{ castellano: "Ruidoso", euskara: "Zaratatsu", level: 3},
			{ castellano: "Jubilado", euskara: "Erretiratu", level: 3},
			{ castellano: "Fichero", euskara: "Fitxategi", level: 3},
			{ castellano: "Archivo", euskara: "Fitxategi", level: 3},
			{ castellano: "Perfil lingüístico", euskara: "Hikuntza-eskakizun", level: 3},
			{ castellano: "Curso (año académico)", euskara: "Ikasturte", level: 3},
			{ castellano: "Pronunciar", euskara: "Ahoskatu", level: 3},
			{ castellano: "Raro", euskara: "Arraroa", level: 3},
			{ castellano: "Vascoparlante", euskara: "Euskal hiztun", level: 3},
			{ castellano: "Dificultad", euskara: "Zailtasun", level: 3},
			{ castellano: "Consejo", euskara: "Aholku", level: 3},
			{ castellano: "Práctica conversación", euskara: "Mintzapractika", level: 3},
			{ castellano: "Nos hemos besado", euskara: "Elkar musukatu dugu", level: 3},
			{ castellano: "Relación", euskara: "Harreman", level: 3},
			{ castellano: "Paro, desempleo", euskara: "Langabezia", level: 3},
			{ castellano: "Locutorio", euskara: "Mintzaleku", level: 3},
			{ castellano: "Colgado", euskara: "Zintzilik", level: 3},
			{ castellano: "Tendido", euskara: "Zintzilik", level: 3},
			{ castellano: "Antiguo", euskara: "Aspaldiko", level: 3},
			{ castellano: "De joven", euskara: "Gaztetako", level: 3},
			{ castellano: "De joven", euskara: "Gaztetan", level: 3},
			{ castellano: "Continuar", euskara: "Jarraitu", level: 3},
			{ castellano: "Pasado", euskara: "Lehenaldi", level: 3},
			{ castellano: "De ojos negros", euskara: "Begibeltz", level: 3},
			{ castellano: "De ojos verdes", euskara: "Begiberde", level: 3},
			{ castellano: "De ojos grandes", euskara: "Begihandi", level: 3},
			{ castellano: "De espalda ancha", euskara: "Bizkarzabal", level: 3},
			{ castellano: "Calvo", euskara: "Burusoil", level: 3},
			{ castellano: "De labios finos", euskara: "Ezpainestu", level: 3},
			{ castellano: "Pelinegro", euskara: "Ilebeltz", level: 3},
			{ castellano: "Rubio", euskara: "Ilehori", level: 3},
			{ castellano: "De pelo rizado", euskara: "Ilekizkur", level: 3},
			{ castellano: "De cara sonrosada", euskara: "Musugorri", level: 3},
			{ castellano: "Fuerte", euskara: "Sendo", level: 3},
			{ castellano: "Robusto", euskara: "Sendo", level: 3},
			{ castellano: "Narigudo", euskara: "Sudurluze", level: 3},
			{ castellano: "Chato", euskara: "Sudurmotz", level: 3},
			{ castellano: "Juguete", euskara: "Jostailu", level: 3},
			{ castellano: "Montón", euskara: "Pilo", level: 3},
			{ castellano: "Sencillo", euskara: "Xume", level: 3},
			{ castellano: "Modesto", euskara: "Xume", level: 3},
			{ castellano: "Peonza", euskara: "Ziba", level: 3},
			{ castellano: "Pues entonces", euskara: "Bada", level: 3},
			{ castellano: "Por lo menos", euskara: "Behintzat", level: 3},
			{ castellano: "Desván", euskara: "Ganbara", level: 3},
			{ castellano: "¡Vamos!", euskara: "Goazen!", level: 3},
			{ castellano: "Feo", euskara: "Itsusi", level: 3},
			{ castellano: "Joyería", euskara: "Bitxi-denda", level: 3},
			{ castellano: "Reclamación", euskara: "Erreklamazio", level: 3},
			{ castellano: "Apodo", euskara: "Ezizen", level: 3},
			{ castellano: "Identificación", euskara: "Identifikatze-lan", level: 3},
			{ castellano: "Ladrón", euskara: "Lapur", level: 3},
			{ castellano: "Testigo", euskara: "Lekuko", level: 3},
			{ castellano: "Sospechoso", euskara: "Susmagarri", level: 3},
			{ castellano: "Testimonio", euskara: "Testigantza", level: 3},
			{ castellano: "Detalle", euskara: "Xehetasun", level: 3},
			{ castellano: "Detalle", euskara: "Zehaztasun", level: 3},
			{ castellano: "Camisa", euskara: "Alkandora", level: 3},
			{ castellano: "Abrigo", euskara: "Beroki", level: 3},
			{ castellano: "Visera", euskara: "Bisera", level: 3},
			{ castellano: "Peculiar", euskara: "Bitxi", level: 3},
			{ castellano: "Barba", euskara: "Bizar", level: 3},
			{ castellano: "Chaqueta", euskara: "Jaka", level: 3},
			{ castellano: "Rizado", euskara: "Kizkur", level: 3},
			{ castellano: "Largo", euskara: "Luze", level: 3},
			{ castellano: "Comisaría", euskara: "Polizia-etxe", level: 3},
			{ castellano: "Pantalón vaquero", euskara: "Praka bakero", level: 3},
			{ castellano: "Ancho", euskara: "Zabal", level: 3},
			{ castellano: "¡Vaya sorpresa!", euskara: "A zer sorpresa!", level: 3},
			{ castellano: "Hogar del jubilado", euskara: "Zahar-etxe", level: 3},
			{ castellano: "¡Cómo han cambiado las cosas!", euskara: "Zenbat aldatu diren gauzak!", level: 3},
			{ castellano: "Solo", euskara: "Bakarrik", level: 3},
			{ castellano: "¡Cómo ha cambiado la escuela!", euskara: "Nola aldatu den eskola!", level: 3},
			{ castellano: "Tarima", euskara: "Oholtza", level: 3},
			{ castellano: "Celebrar", euskara: "Ospatu", level: 3},
			{ castellano: "Maestro", euskara: "Maisu", level: 3},
			{ castellano: "Aniversario", euskara: "Urteurren", level: 3},
			{ castellano: "Extranjero (país)", euskara: "Atzerri", level: 3},
			{ castellano: "Extranjero (persona)", euskara: "Atzerritar", level: 3},
			{ castellano: "Caracol", euskara: "Barraskilo", level: 3},
			{ castellano: "Tomar para sí", euskara: "Berea egin", level: 3},
			{ castellano: "Hacer suyo", euskara: "Berea egin", level: 3},
			{ castellano: "Gusto", euskara: "Gustu", level: 3},
			{ castellano: "Sidra", euskara: "Sagardo", level: 3},
			{ castellano: "Programa (TV)", euskara: "Saio", level: 3},
			{ castellano: "Afición", euskara: "Zaletasun", level: 3},
			{ castellano: "Lugar cubierto", euskara: "Aterpe", level: 3},
			{ castellano: "Carril bici", euskara: "Bidegorri", level: 3},
			{ castellano: "Pasatiempo", euskara: "Denbora-pasa", level: 3},
			{ castellano: "Actual", euskara: "Egungo", level: 3},
			{ castellano: "Jugar a fútbol", euskara: "Futbolean jokatu", level: 3},
			{ castellano: "Coger", euskara: "Harrapatu", level: 3},
			{ castellano: "Juego", euskara: "Jolas", level: 3},
			{ castellano: "Lugar de recreo", euskara: "Jolastoki", level: 3},
			{ castellano: "Jaula pequeña", euskara: "Kaiolatxo", level: 3},
			{ castellano: "Grillo", euskara: "Kiker", level: 3},
			{ castellano: "Patinar", euskara: "Patinatu", level: 3},
			{ castellano: "Comba", euskara: "Soka", level: 3},
			{ castellano: "Saltar a la comba", euskara: "Sokasaltoan ibili", level: 3},
			{ castellano: "Jugar a qué", euskara: "Zertan jokatu", level: 3},
			{ castellano: "Bicho", euskara: "Zumorro", level: 3},
			{ castellano: "Agujero", euskara: "Zulo", level: 3},
			{ castellano: "Teatro", euskara: "Antzerki", level: 3},
			{ castellano: "Pelearse", euskara: "Borrokan ibili", level: 3},
			{ castellano: "Hábil", euskara: "Trebe", level: 3},
			{ castellano: "Jugar a la pelota", euskara: "Pilotan jokatu", level: 3},
			{ castellano: "Campeonato", euskara: "Txapelketa", level: 3},
			{ castellano: "Jugar a chapas", euskara: "Txapetan jokatu", level: 3},
			{ castellano: "Agosto", euskara: "Abuztua", level: 3},
			{ castellano: "Mi hermana y yo", euskara: "Nire ahizpa eta biok", level: 3},
			{ castellano: "Desear", euskara: "Desiratu", level: 3},
			{ castellano: "Programa de radio", euskara: "Irratsaio", level: 3},
			{ castellano: "Vacaciones", euskara: "Oporrak", level: 3},
			{ castellano: "Disfrutar de vacaciones", euskara: "Oporrez gozatu", level: 3},
			{ castellano: "Dinero", euskara: "Dirua, sos", level: 3},
			{ castellano: "Verano", euskara: "Uda", level: 3},
			{ castellano: "Julio", euskara: "Uztaila", level: 3},
			{ castellano: "¡Qué recuerdos!", euskara: "A zer oroitzapenak haiek!", level: 3},
			{ castellano: "Iglesia", euskara: "Eliza", level: 3},
			{ castellano: "Vergüenza", euskara: "Lotsa", level: 3},
			{ castellano: "Melancólico", euskara: "Malenkorriatsu", level: 3},
			{ castellano: "Misa", euskara: "Meza", level: 3},
			{ castellano: "Recuerdo", euskara: "Oroitzapen", level: 3},
			{ castellano: "Buzón", euskara: "Postontzi", level: 3},
			{ castellano: "Detener", euskara: "Atxilotu", level: 3},
			{ castellano: "Por la parte de atrás", euskara: "Atzeko aldetik", level: 3},
			{ castellano: "De repente", euskara: "Bat-batean", level: 3},
			{ castellano: "De pronto", euskara: "Bat-batean", level: 3},
			{ castellano: "Inmediatamente", euskara: "Berehala", level: 3},
			{ castellano: "Cuchillo", euskara: "Labana", level: 3},
			{ castellano: "Navaja", euskara: "Labana", level: 3},
			{ castellano: "Robo", euskara: "Lapurreta", level: 3},
			{ castellano: "Atraco", euskara: "Lapurreta", level: 3},
			{ castellano: "Entonces", euskara: "Orduan", level: 3},
			{ castellano: "Nervioso", euskara: "Urduri", level: 3},
			{ castellano: "Cantante", euskara: "Abeslari", level: 3},
			{ castellano: "Sociedad", euskara: "Gizarte", level: 3},
			{ castellano: "Sonriente", euskara: "Irribarretsu", level: 3},
			{ castellano: "Antes de ayer", euskara: "Herenegun", level: 3},
			{ castellano: "Andamio", euskara: "Andamio", level: 3},
			{ castellano: "Ayer mismo", euskara: "Atzo bertan", level: 3},
			{ castellano: "Grave", euskara: "Larri", level: 3},
			{ castellano: "Torcer", euskara: "Okertu", level: 3},
			{ castellano: "Aventurero", euskara: "Abenturazale", level: 3},
			{ castellano: "Al revés", euskara: "Alderantziz", level: 3},
			{ castellano: "Animador", euskara: "Animatzaile", level: 3},
			{ castellano: "Problema", euskara: "Arazo", level: 3},
			{ castellano: "Al final", euskara: "Azkenean", level: 3},
			{ castellano: "Barco de vela", euskara: "Belaontzi", level: 3},
			{ castellano: "Vuelta", euskara: "Bira", level: 3},
			{ castellano: "Acción", euskara: "Ekintza", level: 3},
			{ castellano: "Actividad", euskara: "Ekintza", level: 3},
			{ castellano: "Decisión", euskara: "EraFbakia", level: 3},
			{ castellano: "Estar en contacto", euskara: "Harremanetan egon", level: 3},
			{ castellano: "Deportista", euskara: "Kirolari", level: 3},
			{ castellano: "Medio de comunicación", euskara: "Komunikabide", level: 3},
			{ castellano: "Rueda de prensa", euskara: "Prentsaurreko", level: 3},
			{ castellano: "Divulgar", euskara: "Zabaldu", level: 3},
			{ castellano: "Seguramente", euskara: "Ziurrenik", level: 3},
			{ castellano: "Suerte", euskara: "Zorte", level: 3},
			{ castellano: "Corriente", euskara: "Arrunta", level: 3},
			{ castellano: "Común", euskara: "Arrunta", level: 3},
			{ castellano: "Que sí", euskara: "Baietz", level: 3},
			{ castellano: "De otro tipo", euskara: "Bestelako", level: 3},
			{ castellano: "Bebido", euskara: "Edanda", level: 3},
			{ castellano: "Situación", euskara: "Egoera", level: 3},
			{ castellano: "Estado", euskara: "Egoera", level: 3},
			{ castellano: "Nieve", euskara: "Elur", level: 3},
			{ castellano: "Conductor", euskara: "Gidari", level: 3},
			{ castellano: "Conducir", euskara: "Gidatu", level: 3},
			{ castellano: "Humano", euskara: "Gizaki", level: 3},
			{ castellano: "Tener sueño", euskara: "Logura izan", level: 3},
			{ castellano: "En todo momento", euskara: "Une oro", level: 3},
			{ castellano: "Citar", euskara: "Aipatu", level: 3},
			{ castellano: "Mencionar", euskara: "Aipatu", level: 3},
			{ castellano: "Descanso", euskara: "Atseden", level: 3},
			{ castellano: "Adelantamiento", euskara: "Aurreratze", level: 3},
			{ castellano: "Inadecuado", euskara: "Desegoki", level: 3},
			{ castellano: "Entorno", euskara: "Inguru", level: 3},
			{ castellano: "Alrededores", euskara: "Inguru", level: 3},
			{ castellano: "Hielo", euskara: "Izotz", level: 3},
			{ castellano: "Moderno", euskara: "Moderno", level: 3},
			{ castellano: "Corto", euskara: "Motz", level: 3},
			{ castellano: "Confusión", euskara: "Nahaste", level: 3},
			{ castellano: "Bolsillo", euskara: "Poltsiko", level: 3},
			{ castellano: "Ropa", euskara: "Arropa", level: 3},
			{ castellano: "Ropa", euskara: "Jantzi", level: 3},
			{ castellano: "Responsable", euskara: "Arduradun", level: 3},
			{ castellano: "Actualizar", euskara: "Eguneratu", level: 3},
			{ castellano: "Perder", euskara: "Galdu", level: 3},
			{ castellano: "Oficina de objetos perdidos", euskara: "Galdutako objetuen bulego", level: 3},
			{ castellano: "Que sirve de ayuda", euskara: "Lagungarri", level: 3},
			{ castellano: "Objeto", euskara: "Objetu", level: 3},
			{ castellano: "Tamaño", euskara: "Tamaina", level: 3},
			{ castellano: "Tamaño", euskara: "Neurri", level: 3},
			{ castellano: "Búsqueda", euskara: "Topatze-lan", level: 3},
			{ castellano: "Algo", euskara: "Zerbait", level: 3},
			{ castellano: "Alguna cosa", euskara: "Zerbait", level: 3},
			{ castellano: "Aluminio", euskara: "Aluminio", level: 3},
			{ castellano: "Lana", euskara: "Artile", level: 3},
			{ castellano: "Cuero", euskara: "Larru", level: 3},
			{ castellano: "Piel", euskara: "Larru", level: 3},
			{ castellano: "Plástico", euskara: "Plastiko", level: 3},
			{ castellano: "Titanio", euskara: "Titanio", level: 3},
			{ castellano: "Oro", euskara: "Urre", level: 3},
			{ castellano: "Seda", euskara: "Zeta", level: 3},
			{ castellano: "Plata", euskara: "Zilar", level: 3},
			{ castellano: "Quizás", euskara: "Agian", level: 3},
			{ castellano: "Encontrar", euskara: "Aurkitu", level: 3},
			{ castellano: "Redondo", euskara: "Biribil", level: 3},
			{ castellano: "Ciudadano", euskara: "Herritar", level: 3},
			{ castellano: "Recoger", euskara: "Jaso", level: 3},
			{ castellano: "La semana pasada", euskara: "Lehengo astean", level: 3},
			{ castellano: "Suave", euskara: "Leun", level: 3},
			{ castellano: "¡Qué pena!", euskara: "Zer pena!", level: 3},
			{ castellano: "Alpargata", euskara: "Apreta", level: 3},
			{ castellano: "Día de la semana", euskara: "Astegun", level: 3},
			{ castellano: "Uña", euskara: "Azazkal", level: 3},
			{ castellano: "Trabajador social", euskara: "Gizarte-langile", level: 3},
			{ castellano: "Gordo", euskara: "Gizen", level: 3},
			{ castellano: "Falda", euskara: "Gona", level: 3},
			{ castellano: "Calzado deportivo", euskara: "Kirol-oinetako", level: 3},
			{ castellano: "De tacón", euskara: "Takoidun", level: 3},
			{ castellano: "Bastante", euskara: "Nakiho", level: 3},
			{ castellano: "Encontrar", euskara: "Topatu", level: 3},
			{ castellano: "Envejecer", euskara: "Zahartu", level: 3},
			{ castellano: "Lleno de arrugas", euskara: "Zimurrez Beteta", level: 3},
			{ castellano: "Con muchas arrugas", euskara: "Zimurtsu", level: 3},
			{ castellano: "Agradable", euskara: "Atsegin", level: 3},
			{ castellano: "Internado", euskara: "Barnetegi", level: 3},
			{ castellano: "Cabaña", euskara: "Borda", level: 3},
			{ castellano: "Núcleo urbano", euskara: "Herrigune", level: 3},
			{ castellano: "Compañero de estudios", euskara: "Ikaskide", level: 3},
			{ castellano: "Escaso", euskara: "Kaskar", level: 3},
			{ castellano: "Lugar", euskara: "Leku", level: 3},
			{ castellano: "Lugar", euskara: "Toki", level: 3},
			{ castellano: "Lugar", euskara: "Paraje", level: 3},
			{ castellano: "Hostal", euskara: "Ostatu", level: 3},
			{ castellano: "Pera eso", euskara: "Horretarako", level: 3},
			{ castellano: "Ayuda", euskara: "Laguntza", level: 3},
			{ castellano: "Atadura", euskara: "Lotura", level: 3},
			{ castellano: "Persona mayor", euskara: "Nagusi", level: 3},
			{ castellano: "Amante", euskara: "Amorante", level: 3},
			{ castellano: "Idóneo", euskara: "Apropos", level: 3},
			{ castellano: "Separar", euskara: "Banandu", level: 3},
			{ castellano: "Pobre", euskara: "Gajo", level: 3},
			{ castellano: "Así", euskara: "Horrela", level: 3},
			{ castellano: "Peluquería", euskara: "Ile apaindegi", level: 3},
			{ castellano: "Creer", euskara: "Sinetsi", level: 3},
			{ castellano: "Cuchicheo", euskara: "Txutxu-mutxu", level: 3},
			{ castellano: "Cotilleo", euskara: "Txutxu-mutxu", level: 3},
			{ castellano: "Rumor", euskara: "Zurrumurru", level: 3},
			{ castellano: "Quién sabe", euskara: "Auskalo", level: 3},
			{ castellano: "A saber", euskara: "Auskalo", level: 3},
			{ castellano: "El mismo, la misma", euskara: "Berbera", level: 3},
			{ castellano: "Significado", euskara: "Esanahi", level: 3},
			{ castellano: "Nada", euskara: "Ezer ez", level: 3},
			{ castellano: "Extrañado", euskara: "Harrituta", level: 3},
			{ castellano: "Este mismo / esta misma", euskara: "Hauxe", level: 3},
			{ castellano: "Notar", euskara: "Igarri", level: 3},
			{ castellano: "Adivinar", euskara: "Igarri", level: 3},
			{ castellano: "Condiciones laborales", euskara: "Lan baldintzak", level: 3},
			{ castellano: "De momento", euskara: "Oraingoz", level: 3},
			{ castellano: "Sin querer", euskara: "Nahi gabe", level: 3},
			{ castellano: "En principio", euskara: "Printzipioz", level: 3},
			{ castellano: "Seguramente", euskara: "Seguruenik", level: 3},
			{ castellano: "Sospecha", euskara: "Susmo", level: 3},
			{ castellano: "Momento", euskara: "Une", level: 3},
			{ castellano: "Extender(se)", euskara: "Zabaldu", level: 3},
			{ castellano: "¿De veras?", euskara: "Benetan?", level: 3},
			{ castellano: "¡No será verdad!", euskara: "Ez da egia izango!", level: 3},
			{ castellano: "¡Claro que no!", euskara: "Ez, horixe!", level: 3},
			{ castellano: "¡Es terrible!", euskara: "Izugarria da!", level: 3},
			{ castellano: "Proteger", euskara: "Babestu", level: 3},
			{ castellano: "Hueso", euskara: "Hezur", level: 3},
			{ castellano: "Relato, suceso", euskara: "Istorio", level: 3},
			{ castellano: "Confuso", euskara: "Nahasia", level: 3},
			{ castellano: "Todavía", euskara: "Oraindik", level: 3},
			{ castellano: "Lobo", euskara: "Otso", level: 3},
			{ castellano: "Pidiendo consejo", euskara: "Aholku eske", level: 3},
			{ castellano: "Cambio", euskara: "Aldaketa", level: 3},
			{ castellano: "Continuamente", euskara: "Etengabe", level: 3},
			{ castellano: "Que gusta", euskara: "Gustoko", level: 3},
			{ castellano: "Agradable", euskara: "Gustoko", level: 3},
			{ castellano: "Rabieta", euskara: "Kasketa", level: 3},
			{ castellano: "Preocupado", euskara: "Kezkatuta", level: 3},
			{ castellano: "Llorón", euskara: "Negarti", level: 3},
			{ castellano: "Aceptar", euskara: "Onartu", level: 3},
			{ castellano: "Acostumbrarse", euskara: "Ohitu", level: 3},
			{ castellano: "Hablador", euskara: "Hiztuna", level: 3},
			{ castellano: "Pañal", euskara: "Pixoihal", level: 3},
			{ castellano: "Optimista", euskara: "Baikorra", level: 3},
			{ castellano: "Época", euskara: "Oro", level: 3},
			{ castellano: "Carnaval", euskara: "Inauteri", level: 3},
			{ castellano: "Sombrero", euskara: "Kapela", level: 3},
			{ castellano: "Ramo de flores", euskara: "Lore-sorta", level: 3},
			{ castellano: "Globo", euskara: "Puxika", level: 3},
			{ castellano: "Dando volteretas", euskara: "Zilipurdika", level: 3},
			{ castellano: "A cada uno", euskara: "Bana", level: 3},
			{ castellano: "Aquí mismo", euskara: "Hemen(txe) bertan", level: 3},
			{ castellano: "Ahí mismo", euskara: "Hor(txe) bertan", level: 3},
			{ castellano: "Ahí mismo", euskara: "Hortxe", level: 3},
			{ castellano: "Allí mismo", euskara: "Hantxe", level: 3},
			{ castellano: "Allí mismo", euskara: "Han(txe) bertan", level: 3},
			{ castellano: "Travesura", euskara: "Bihurrikeria", level: 3},
			{ castellano: "Por ahora", euskara: "Oraingoz", level: 3},
			{ castellano: "Descansar", euskara: "Atseden hartu", level: 3},
			{ castellano: "Habitante de un caserio", euskara: "Baserritar", level: 3},
			{ castellano: "Campesino", euskara: "Baserritar", level: 3},
			{ castellano: "Quehacer", euskara: "Eginkizun", level: 3},
			{ castellano: "Quehacer", euskara: "Zeregin", level: 3},
			{ castellano: "Tarea", euskara: "Eginkizun", level: 3},
			{ castellano: "Enfermero", euskara: "Erizain", level: 3},
			{ castellano: "Escapada", euskara: "Eskapada", level: 3},
			{ castellano: "Ganado", euskara: "Ganadu", level: 3},
			{ castellano: "Profesión", euskara: "Lanbide", level: 3},
			{ castellano: "Sustituto", euskara: "Ordezo", level: 3},
			{ castellano: "Guia turístico", euskara: "Turismo gidari", level: 3},
			{ castellano: "Explicación", euskara: "Azalpen", level: 3},
			{ castellano: "Si no", euskara: "Bestela", level: 3},
			{ castellano: "De lo contrario", euskara: "Bestela", level: 3},
			{ castellano: "Hora de vestirse", euskara: "Janzteko garaia", level: 3},
			{ castellano: "Tener en cuenta", euskara: "Kontuan hartu", level: 3},
			{ castellano: "Golosina", euskara: "Litxarreria", level: 3},
			{ castellano: "Tienda de golosinas", euskara: "Litxarreria-denda", level: 3},
			{ castellano: "Tobogán", euskara: "Txirrista", level: 3},
			{ castellano: "Cada dos años", euskara: "Bi urtetik behin", level: 3},
			{ castellano: "Sistema de drenaje", euskara: "Dranatze-sistema", level: 3},
			{ castellano: "Solana (lugar orientado al sur)", euskara: "Egutera", level: 3},
			{ castellano: "Cada quince días", euskara: "Hamabost egunetik behin", level: 3},
			{ castellano: "Crecer", euskara: "Hazi", level: 3},
			{ castellano: "Planta", euskara: "Landare", level: 3},
			{ castellano: "Mantener", euskara: "Mantendu", level: 3},
			{ castellano: "Invierno", euskara: "Negua", level: 3},
			{ castellano: "Abono líquido", euskara: "Ongarri likido", level: 3},
			{ castellano: "Primavera", euskara: "Udaberri", level: 3},
			{ castellano: "Cada cuánto tiempo", euskara: "Zenbatetik behin", level: 3},
			{ castellano: "Jefe", euskara: "Buru", level: 3},
			{ castellano: "A relevos", euskara: "Erreleboka", level: 3},
			{ castellano: "Comarca", euskara: "Eskualde", level: 3},
			{ castellano: "Desconocido", euskara: "Ezezagun", level: 3},
			{ castellano: "Ascensor", euskara: "Igogailu", level: 3},
			{ castellano: "Curso", euskara: "Ikastaro", level: 3},
			{ castellano: "Cursillo", euskara: "Ikastaro", level: 3},
			{ castellano: "Verter", euskara: "Isuri", level: 3},
			{ castellano: "Derramar", euskara: "Isuri", level: 3},
			{ castellano: "Alguna urgencia", euskara: "Larrialdiren bat", level: 3},
			{ castellano: "Unido", euskara: "Lotuta", level: 3},
			{ castellano: "Mayor", euskara: "Nagusi", level: 3},
			{ castellano: "Salvamento", euskara: "Salvamendu", level: 3},
			{ castellano: "Bombero", euskara: "Suhiltzaile", level: 3},
			{ castellano: "A gran velocidad", euskara: "Ziztu bizian", level: 3},
			{ castellano: "Justificante", euskara: "Frogagiri", level: 3},
			{ castellano: "Guía", euskara: "Gide", level: 3},
			{ castellano: "Visible", euskara: "Ikusgai", level: 3},
			{ castellano: "Cláusula", euskara: "Klausula", level: 3},
			{ castellano: "Comparar", euskara: "Konparatu", level: 3},
			{ castellano: "Producto", euskara: "Produktu", level: 3},
			{ castellano: "Señal", euskara: "Seinale", level: 3},
			{ castellano: "Firmar", euskara: "Sinatu", level: 3},
			{ castellano: "Sitio dudoso", euskara: "Zalantzazko toki", level: 3},
			{ castellano: "Lista", euskara: "Zerrenda", level: 3},
			{ castellano: "Persona mayor", euskara: "Adineko", level: 3},
			{ castellano: "Acumulación de coches", euskara: "Auto-pilaketa", level: 3},
			{ castellano: "Transporte", euskara: "Garraio", level: 3},
			{ castellano: "Medio de transporte", euskara: "Garraiobide", level: 3},
			{ castellano: "Encuestado", euskara: "Inkestatu", level: 3},
			{ castellano: "Fuera", euskara: "Kanpo", level: 3},
			{ castellano: "Horas punta", euskara: "Puntako ordu", level: 3},
			{ castellano: "Noticia", euskara: "Albiste, berri", level: 3},
			{ castellano: "Estudio", euskara: "Azterlan", level: 3},
			{ castellano: "Por medio de", euskara: "Bidez", level: 3},
			{ castellano: "Bastante", euskara: "Dezente", level: 3},
			{ castellano: "Tendencia", euskara: "Joera", level: 3},
			{ castellano: "Mercado", euskara: "Merkatu", level: 3},
			{ castellano: "Comida precocinada", euskara: "Aurrez prestatuko janari", level: 3},
			{ castellano: "Solamente", euskara: "Bakarrik", level: 3},
			{ castellano: "Hipermercado", euskara: "Hipermerkatu", level: 3},
			{ castellano: "Encuestador", euskara: "Inkestzaile", level: 3},
			{ castellano: "Congelado", euskara: "Izoztu", level: 3},
			{ castellano: "Frecuencia", euskara: "Maiztasun", level: 3},
			{ castellano: "Éxito", euskara: "Arrakasta", level: 3},
			{ castellano: "Hortaliza", euskara: "Barazki", level: 3},
			{ castellano: "En busca de...", euskara: "(e)n bila", level: 3},
			{ castellano: "Producir", euskara: "Ekoitzi", level: 3},
			{ castellano: "Juntarse", euskara: "Elkartu", level: 3},
			{ castellano: "Cómodo", euskara: "Eroso", level: 3},
			{ castellano: "Objetivo", euskara: "Helburu", level: 3},
			{ castellano: "Cesta", euskara: "Otarre", level: 3},
			{ castellano: "En paquetes", euskara: "Paketeetan", level: 3},
			{ castellano: "Solamente", euskara: "Soilik", level: 3},
			{ castellano: "Carne de ternera", euskara: "Txahal-haragi", level: 3},
			{ castellano: "Directamente", euskara: "Zuzenean", level: 3},
			{ castellano: "Piel", euskara: "Azal", level: 3},
			{ castellano: "Valoración", euskara: "Balorazio", level: 3},
			{ castellano: "Mucho tiempo", euskara: "Denbora luze", level: 3},
			{ castellano: "Del gusto de", euskara: "Gustuko", level: 3},
			{ castellano: "A gusto", euskara: "Gustora", level: 3},
			{ castellano: "Pringoso", euskara: "Koipetsu", level: 3},
			{ castellano: "Cosmética ecológica", euskara: "Kostmetika ekologikoa", level: 3},
			{ castellano: "Crema", euskara: "Krema", level: 3},
			{ castellano: "Marca", euskara: "Marka", level: 3},
			{ castellano: "Tambor", euskara: "Danbor", level: 3},
			{ castellano: "Adecuado", euskara: "Egoki", level: 3},
			{ castellano: "Lavadora" , euskara: "Garbigailu", level: 3},
			{ castellano: "Sofisticado", euskara: "Sofistikatu", level: 3},
			{ castellano: "Defectuoso", euskara: "Akastun", level: 3},
			{ castellano: "Servicio de atención", euskara: "Arreta-zerbitzu", level: 3},
			{ castellano: "Últimamente", euskara: "Azkenaldi", level: 3},
			{ castellano: "Perdón", euskara: "Barkamen", level: 3},
			{ castellano: "Contestador automático", euskara: "Erantzungailu automatiko", level: 3},
			{ castellano: "Imprescindible", euskara: "Ezinbesteko", level: 3},
			{ castellano: "Pérdida", euskara: "Galera", level: 3},
			{ castellano: "Más veces", euskara: "Gehiagotan", level: 3},
			{ castellano: "Excesivo", euskara: "Gehiegizko", level: 3},
			{ castellano: "Para tanto", euskara: "Hainbesterako", level: 3},
			{ castellano: "Enfado", euskara: "Haserre", level: 3},
			{ castellano: "Enfadado", euskara: "Haserre", level: 3},
			{ castellano: "Importar", euskara: "Inporta izan", level: 3},
			{ castellano: "Quejarse", euskara: "Kexatu", level: 3},
			{ castellano: "Complicado", euskara: "Konplexu", level: 3},
			{ castellano: "Consumidor", euskara: "Kontsumitzaile", level: 3},
			{ castellano: "Primera vez", euskara: "Lehenengo aldi", level: 3},
			{ castellano: "Antes de nada", euskara: "Lehenik eta behin", level: 3},
			{ castellano: "Avería", euskara: "Matxura", level: 3},
			{ castellano: "Madera", euskara: "Egur", level: 3},
			{ castellano: "Ahora mismo", euskara: "Oraintxe bertan", level: 3},
			{ castellano: "Increíble", euskara: "Sinestezin", level: 3},
			{ castellano: "Mueble", euskara: "Altzari", level: 3},
			{ castellano: "Reforma", euskara: "Berritze-lan", level: 3},
			{ castellano: "Obras de reparación", euskara: "Konponketa-lan", level: 3},
			{ castellano: "Contrario", euskara: "Kontrako", level: 3},
			{ castellano: "Jefe de obra", euskara: "Obra-arduradun", level: 3},
			{ castellano: "Pared", euskara: "Pareta", level: 3},
			{ castellano: "Suelo", euskara: "Zoru", level: 3},
			{ castellano: "¡Oye!", euskara: "Aizu!", level: 3},
			{ castellano: "Hora de comer al mediodía", euskara: "Bazkalordu", level: 3},
			{ castellano: "¡Mira!, ¡Mirad!", euskara: "Begira!", level: 3},
			{ castellano: "Descuido", euskara: "Deskuidu", level: 3},
			{ castellano: "Poso", euskara: "Hondar", level: 3},
			{ castellano: "Equivocarse", euskara: "Nahasi", level: 3},
			{ castellano: "Plato combinado", euskara: "Plater konbinatu", level: 3},
			{ castellano: "Plato (contenido)", euskara: "Platerkada", level: 3},
			{ castellano: "Hora de cenar", euskara: "Afalordu", level: 3},
			{ castellano: "Champiñón", euskara: "Barrengorri", level: 3},
			{ castellano: "Nata", euskara: "Esne-gain", level: 3},
			{ castellano: "Fresa", euskara: "Marrubi", level: 3},
			{ castellano: "Bocadillo", euskara: "Ogitarteko", level: 3},
			{ castellano: "Pimiento", euskara: "Piper", level: 3},
			{ castellano: "Reclamar", euskara: "Erreklamatu", level: 3},
			{ castellano: "Escaso", euskara: "Eskas", level: 3},
			{ castellano: "Llave", euskara: "Giltza", level: 3},
			{ castellano: "Besar", euskara: "Musukatu", level: 3},
			{ castellano: "Red social", euskara: "Sare sozial", level: 3},
			{ castellano: "Chatear", euskara: "Txateatu", level: 3},
			{ castellano: "Sobre qué", euskara: "Zeri buruz", level: 3},
			{ castellano: "De qué", euskara: "Zeri buruz", level: 3},
			{ castellano: "Baile de salón", euskara: "Areto-dantza", level: 3},
			{ castellano: "Encuesta", euskara: "Inkesta", level: 3},
			{ castellano: "Día festivo", euskara: "Jaiegun", level: 3},
			{ castellano: "Asociación de montaña", euskara: "Mendi elkarte", level: 3},
			{ castellano: "Excursión", euskara: "Txangoa", level: 3},
			{ castellano: "Empresa de ropa", euskara: "Arropa empresa", level: 3},
			{ castellano: "Modo de vida", euskara: "Bizimodu", level: 3},
			{ castellano: "Adecuarse", euskara: "Egokitu", level: 3},
			{ castellano: "Adaptarse", euskara: "Egokitu", level: 3},
			{ castellano: "Mediodía", euskara: "Eguerdi", level: 3},
			{ castellano: "Diario", euskara: "Eguneroko", level: 3},
			{ castellano: "De todos los días", euskara: "Eguneroko", level: 3},
			{ castellano: "Rutina", euskara: "Errutina", level: 3},
			{ castellano: "Tumbarse", euskara: "Etzan", level: 3},
			{ castellano: "Atareado, ocupado", euskara: "Lanpetuta", level: 3},
			{ castellano: "Lugar de trabajo", euskara: "Lantoki", level: 3},
			{ castellano: "Planchar", euskara: "Lisatu", level: 3},
			{ castellano: "Acostarse", euskara: "Oheratu", level: 3},
			{ castellano: "Ordenar", euskara: "Txukundu", level: 3},
			{ castellano: "Limpiar", euskara: "Txukundu", level: 3},
			{ castellano: "En busca de los niños", euskara: "Umeen bila", level: 3},
			{ castellano: "Rincón", euskara: "Bazter", level: 3},
			{ castellano: "Colección", euskara: "Bilduma", level: 3},
			{ castellano: "País", euskara: "Herrialde", level: 3},
			{ castellano: "Anochecer", euskara: "Ilunabar", level: 3},
			{ castellano: "Atardecer", euskara: "Ilunabar", level: 3},
			{ castellano: "Cabezada", euskara: "Lo-kuluxka", level: 3},
			{ castellano: "Siesta", euskara: "Lo-kuluxka", level: 3},
			{ castellano: "Acuerdo", euskara: "Adostasun", level: 3},
			{ castellano: "Organizar", euskara: "Antolatu", level: 3},
			{ castellano: "Argumento", euskara: "Argudio", level: 3},
			{ castellano: "Ahorrar", euskara: "Aurreztu", level: 3},
			{ castellano: "Mercadillo", euskara: "Azoka-txiki", level: 3},
			{ castellano: "Pendiente", euskara: "Belarritako", level: 3},
			{ castellano: "Número de votos", euskara: "Boto kopuru", level: 3},
			{ castellano: "Votar", euskara: "Bozkatu", level: 3},
			{ castellano: "Sortija", euskara: "Eskulan", level: 3},
			{ castellano: "Viaje de fin de curso", euskara: "Ikasturte bukaerako bidai", level: 3},
			{ castellano: "Opinión", euskara: "Iritzi", level: 3},
			{ castellano: "Convenir", euskara: "Komeni Izan", level: 3},
			{ castellano: "Cuenta corriente", euskara: "Kontu korronte", level: 3},
			{ castellano: "Montón", euskara: "Mordo", level: 3},
			{ castellano: "Grupo", euskara: "Mordo", level: 3},
			{ castellano: "Sortear", euskara: "Zozkatu", level: 3},
			{ castellano: "Presupuesto", euskara: "Aurrekontu", level: 3},
			{ castellano: "Vecino", euskara: "Auzoko", level: 3},
			{ castellano: "Vecino", euskara: "Bizilagun", level: 3},
			{ castellano: "Cuanto antes", euskara: "Lehenbailen", level: 3},
			{ castellano: "Coche de niño", euskara: "Ume-kotxe", level: 3},
			{ castellano: "Estar atento", euskara: "Adi egon", level: 3},
			{ castellano: "Reciclar", euskara: "Birziklatu", level: 3},
			{ castellano: "Sonrisa", euskara: "Irribarre", level: 3},
			{ castellano: "Basura", euskara: "Zabor", level: 3},
			{ castellano: "Residuo", euskara: "Zabor", level: 3},
			{ castellano: "Viaje", euskara: "Bidaia", level: 3},
			{ castellano: "Lugar de residencia", euskara: "Bizileku", level: 3},
			{ castellano: "Época", euskara: "Garai", level: 3},
			{ castellano: "De piedra", euskara: "Harrizko", level: 3},
			{ castellano: "Pueblo natal", euskara: "Jaioterri", level: 3},
			{ castellano: "Planta", euskara: "Solairu", level: 3},
			{ castellano: "En qué lugar", euskara: "Zenbatgarren", level: 3},
			{ castellano: "Posición", euskara: "Zenbatgarren", level: 3},
			{ castellano: "¡Vaya cambio!", euskara: "A zer aldaketa!", level: 3},
			{ castellano: "Explicar", euskara: "Azaldu", level: 3},
			{ castellano: "Mercado", euskara: "Azoka", level: 3},
			{ castellano: "Desaparecido", euskara: "Desagertuta", level: 3},
			{ castellano: "Fábrica de galletas", euskara: "Gaileta-fabrika", level: 3},
			{ castellano: "En estos últimos tiempos", euskara: "Garai batetik hona", level: 3},
			{ castellano: "Gasolinera", euskara: "Gasolindegi", level: 3},
			{ castellano: "Imprenta", euskara: "Inprimategi", level: 3},
			{ castellano: "Curiosidad", euskara: "Jakin-min", level: 3},
			{ castellano: "Polideportivo", euskara: "Kiroldegi", level: 3},
			{ castellano: "Fábrica", euskara: "Fabrika", level: 3},
			{ castellano: "Biblioteca", euskara: "Liburutegi", level: 3},
			{ castellano: "Fábrica de lino", euskara: "Lino-fabrika", level: 3},
			{ castellano: "Centro de Salud", euskara: "Osasun zentro", level: 3},
			{ castellano: "Pensión", euskara: "Ostatu", level: 3},
			{ castellano: "Papelera (fábrica)", euskara: "Paper-fabrika", level: 3},
			{ castellano: "¡Cómo han cambiado los pueblos!", euskara: "Zenbat aldatu diren herriak!", level: 3},
			{ castellano: "Puente", euskara: "Zubi", level: 3},
			{ castellano: "Antiguo", euskara: "Garai bateko", level: 3},
			{ castellano: "Aparato", euskara: "Tramankulu", level: 3},
			{ castellano: "Chimenea", euskara: "Beheko sua", level: 3},
			{ castellano: "Horno de madera", euskara: "Egurrezko labe", level: 3},
			{ castellano: "Arcón para salar", euskara: "Gazikutxa", level: 3},
			{ castellano: "Fregadera", euskara: "Harraska", level: 3},
			{ castellano: "Fregadera", euskara: "Konketa", level: 3},
			{ castellano: "Fresquera", euskara: "Hoztegi", level: 3},
			{ castellano: "Radio", euskara: "Irrati", level: 3},
			{ castellano: "Bloque de hielo", euskara: "Izotz bloke", level: 3},
			{ castellano: "Horno", euskara: "Labe", level: 3},
			{ castellano: "Plancha de ropa", euskara: "Lisaburdina", level: 3},
			{ castellano: "Microondas", euskara: "Mikrouhin labe", level: 3},
			{ castellano: "Brasero", euskara: "Sutontzi", level: 3},
			{ castellano: "Sistema de calefacción", euskara: "Berogailu sistema", level: 3},
			{ castellano: "Carbón", euskara: "Ikatz", level: 3},
			{ castellano: "Pizarra", euskara: "Arbela", level: 3},
			{ castellano: "Luminoso", euskara: "Argitsu", level: 3},
			{ castellano: "Repasar", euskara: "Berrikusi", level: 3},
			{ castellano: "Allí mismo", euskara: "Bertan", level: 3},
			{ castellano: "De memoria", euskara: "Buruz", level: 3},
			{ castellano: "Dictado", euskara: "Diktaketa", level: 3},
			{ castellano: "Tema", euskara: "Gai", level: 3},
			{ castellano: "Esquina", euskara: "Izkina", level: 3},
			{ castellano: "Comedor", euskara: "Jangela", level: 3},
			{ castellano: "Comedor", euskara: "Jantoki", level: 3},
			{ castellano: "Cuenta", euskara: "Kontu", level: 3},
			{ castellano: "Cálculo", euskara: "Kontu", level: 3},
			{ castellano: "Colocadas en fila", euskara: "Lerroka ipini", level: 3},
			{ castellano: "A voces", euskara: "Ozenki", level: 3},
			{ castellano: "Charlando", euskara: "Berriketan", level: 3},
			{ castellano: "Cliente", euskara: "Bezero", level: 3},
			{ castellano: "De todo", euskara: "Denet(ar)ik", level: 3},
			{ castellano: "¡Madre mia!", euskara: "Ene, bada!", level: 3},
			{ castellano: "Trabajo de limpieza", euskara: "Garbiketa-lan", level: 3},
			{ castellano: "Recepción", euskara: "Harrera-leku", level: 3},
			{ castellano: "Vacio", euskara: "Hutsik", level: 3},
			{ castellano: "Piscina", euskara: "Igerileku", level: 3},
			{ castellano: "Jardín", euskara: "Lorategi", level: 3},
			{ castellano: "Trabajo de mantenimiento", euskara: "Mantentze-lan", level: 3},
			{ castellano: "Cerradura", euskara: "Sarraila", level: 3},
			{ castellano: "¡Cuántas cosas haces!", euskara: "Zenbat gauza egiten dituzun!", level: 3},
			{ castellano: "Cambiar", euskara: "Aldatu", level: 3},
			{ castellano: "Barrer", euskara: "Eskobatu", level: 3},
			{ castellano: "Limpiar", euskara: "Garbitu", level: 3},
			{ castellano: "Arreglar", euskara: "Konpondu", level: 3},
			{ castellano: "Un beso para cada uno", euskara: "Musu bana", level: 3},
			{ castellano: "Regar", euskara: "Ureztatu", level: 3},
			{ castellano: "Atención", euskara: "Adi", level: 3},
			{ castellano: "Fin de semana", euskara: "Asteburu", level: 3},
			{ castellano: "Ropa de segunda mano", euskara: "Bigarren eskuko arropa", level: 3},
			{ castellano: "Comida casera", euskara: "Etxeko janari", level: 3},
			{ castellano: "Cerveza", euskara: "Garagardo", level: 3},
			{ castellano: "Recuerdos", euskara: "Goraintziak", level: 3},
			{ castellano: "Asombroso", euskara: "Harrigarri", level: 3},
			{ castellano: "Mejorar", euskara: "Hobetu", level: 3},
			{ castellano: "Domingo", euskara: "Igande", level: 3},
			{ castellano: "Hora de comer", euskara: "Jatordu", level: 3},
			{ castellano: "¡Ja, ja!", euskara: "Kar, kar!", level: 3},
			{ castellano: "Cuadrilla", euskara: "Koadrila", level: 3},
			{ castellano: "Sábado", euskara: "Larunbat", level: 3},
			{ castellano: "Mensaje", euskara: "Mezu", level: 3},
			{ castellano: "Arreglar(se)", euskara: "Moldatu", level: 3},
			{ castellano: "Esta vez", euskara: "Oraingoan", level: 3},
			{ castellano: "Mediante e-mail", euskara: "Posta elektronikoz", level: 3},
			{ castellano: "Trabajo de conserje", euskara: "Atezain lan", level: 3},
			{ castellano: "Repartir", euskara: "Banatu", level: 3},
			{ castellano: "Sorpresa, imprevisto", euskara: "Ezuste(ko)", level: 3},
			{ castellano: "Enfermo", euskara: "Gaixorik", level: 3},
			{ castellano: "Trabajo de recepcionista", euskara: "Harregaile lan", level: 3},
			{ castellano: "Correo", euskara: "Posta", level: 3},
			{ castellano: "Servicio", euskara: "Zerbitzu", level: 3},
			{ castellano: "De paso", euskara: "Bide batez", level: 3},
			{ castellano: "Contestador", euskara: "Erantzungailu", level: 3},
			{ castellano: "Vaciar", euskara: "Hustu", level: 3},
			{ castellano: "Secar", euskara: "Lehortu", level: 3},
			{ castellano: "Compartir", euskara: "Partekatu", level: 3},
			{ castellano: "Niebla", euskara: "Laino", level: 3},
			{ castellano: "Dirección General de Tráfico", euskara: "Trafiko Zuzendaritza Nagusia", level: 3},
			{ castellano: "Desganado", euskara: "Alfertuta", level: 3},
			{ castellano: "Por si acaso", euskara: "Badaezpada ere", level: 3},
			{ castellano: "Abrazo", euskara: "Besarkada", level: 3},
			{ castellano: "Por otro lado", euskara: "Bestalde", level: 3},
			{ castellano: "Clase particular", euskara: "Eskola partikularra", level: 3},
			{ castellano: "Carta", euskara: "Gutun", level: 3},
			{ castellano: "Problema, lío", euskara: "Komeria", level: 3},
			{ castellano: "Arreglo", euskara: "Konponketa", level: 3},
			{ castellano: "Cortar", euskara: "Moztu", level: 3},
			{ castellano: "Mover", euskara: "Mugitu", level: 3},
			{ castellano: "Baja de maternidad", euskara: "Amatasun baja", level: 3},
			{ castellano: "Trabajo en equipo", euskara: "Talde-lan", level: 3},
			{ castellano: "Avanzar", euskara: "Aurrera egin", level: 3},
			{ castellano: "Entre otras cosas", euskara: "Besteak veste", level: 3},
			{ castellano: "Importante", euskara: "Garrantzitsu", level: 3},
			{ castellano: "Fuerza", euskara: "Indar", level: 3},
			{ castellano: "Premio", euskara: "Sari", level: 3},
			{ castellano: "Reparto", euskara: "Banaketa", level: 3},
			{ castellano: "Producir, causar", euskara: "Eragin", level: 3},
			{ castellano: "Nochebuena", euskara: "Gabon gaua", level: 3},
			{ castellano: "Costumbre", euskara: "Ohitura", level: 3},
			{ castellano: "Escenario", euskara: "Agertoki", level: 3},
			{ castellano: "Batería (músico)", euskara: "Bateria-jotzaile", level: 3},
			{ castellano: "Peculiar", euskara: "Berezi", level: 3},
			{ castellano: "Sorpresas que no esperamos", euskara: "Espero ez ditugun ustekabeak", level: 3},
			{ castellano: "Foco", euskara: "Foku", level: 3},
			{ castellano: "Asombro", euskara: "Harridura", level: 3},
			{ castellano: "Soprender", euskara: "Harritu", level: 3},
			{ castellano: "Espectáculo", euskara: "Ikuskizun", level: 3},
			{ castellano: "Espectador", euskara: "Ikusle", level: 3},
			{ castellano: "Aspecto", euskara: "Itxura", level: 3},
			{ castellano: "Cantante", euskara: "Kantari", level: 3},
			{ castellano: "Sorpresa", euskara: "Ustekabe", level: 3},
			{ castellano: "Vigilante", euskara: "Zaintzaile", level: 3},
			{ castellano: "Nada", euskara: "Batere", level: 3},
			{ castellano: "En absoluto", euskara: "Batere", level: 3},
			{ castellano: "Familiar", euskara: "Familiarteko", level: 3},
			{ castellano: "Robusto", euskara: "Gihartsu", level: 3},
			{ castellano: "Cuerpo", euskara: "Gorputz", level: 3},
			{ castellano: "Antiguo", euskara: "Antigoaleko", level: 3},
			{ castellano: "Desfasado", euskara: "Antigoaleko", level: 3},
			{ castellano: "Desagradable", euskara: "Desatsegin", level: 3},
			{ castellano: "Confusión", euskara: "Deskuidu", level: 3},
			{ castellano: "Número de referencia", euskara: "Erreferentzia zenbaki", level: 3},
			{ castellano: "Pedido", euskara: "Eskaera", level: 3},
			{ castellano: "Estrecho", euskara: "Estu", level: 3},
			{ castellano: "Corbata", euskara: "Gorbata", level: 3},
			{ castellano: "Cordón", euskara: "Lokarri", level: 3},
			{ castellano: "Manga", euskara: "Mahuka", level: 3},
			{ castellano: "Diseminado", euskara: "Sakabanatuta", level: 3},
			{ castellano: "Cima", euskara: "Tontor", level: 3},
			{ castellano: "Prado", euskara: "Zelai", level: 3},
			{ castellano: "Maravilloso", euskara: "Zoragarri", level: 3},
			{ castellano: "Temporada", euskara: "Bolada", level: 3},
			{ castellano: "Recién llegado", euskara: "Etorberri", level: 3},
			{ castellano: "Encontrarse", euskara: "Topo egin", level: 3},
			{ castellano: "Parecido", euskara: "Antz", level: 3},
			{ castellano: "Parecido", euskara: "Antzekotasuna", level: 3},
			{ castellano: "Color castaño", euskara: "Gaztaina kolore", level: 3},
			{ castellano: "Pariente cercano", euskara: "Senide", level: 3},
			{ castellano: "Familiar", euskara: "Senitarteko", level: 3},
			{ castellano: "Pariente", euskara: "Senitarteko", level: 3},
			{ castellano: "Gordinflón", euskara: "Lodikote", level: 3},
			{ castellano: "Llevarse bien", euskara: "Ondo moldatu", level: 3},
			{ castellano: "Oposición", euskara: "Aurkaritza", level: 3},
			{ castellano: "Vegetariano", euskara: "Begetariano", level: 3},
			{ castellano: "Objeción", euskara: "Eragozpen", level: 3},
			{ castellano: "Actitud", euskara: "Jarrera", level: 3},
			{ castellano: "Contradicción", euskara: "Kontraeran", level: 3},
			{ castellano: "Contrapuesto", euskara: "Kontrajarria", level: 3},
			{ castellano: "Tímido", euskara: "Lotsati", level: 3},
			{ castellano: "Alimentación", euskara: "Elikadura", level: 3},
			{ castellano: "Puro", euskara: "Puru", level: 3},
			{ castellano: "En la época de la escuela", euskara: "Eskola-garaian", level: 3},
			{ castellano: "Apariencia", euskara: "Itxura", level: 3},
			{ castellano: "De una cierta edad", euskara: "Adineko", level: 3},
			{ castellano: "Verdadero", euskara: "Benetako", level: 3},
			{ castellano: "Reescribir", euskara: "Berridatzi", level: 3},
			{ castellano: "¡Y punto!", euskara: "Eta kito!", level: 3},
			{ castellano: "Borrar", euskara: "Ezabatu", level: 3},
			{ castellano: "Conocido", euskara: "Ezaguna", level: 3},
			{ castellano: "Fallar", euskara: "Huts egin", level: 3},
			{ castellano: "Peculiar", euskara: "Xelebre", level: 3},
			{ castellano: "Extravagante", euskara: "Xelebre", level: 3},
			{ castellano: "Asunto de dinero", euskara: "Diru-kontu", level: 3},
			{ castellano: "Futuro", euskara: "Etorkizun", level: 3},
			{ castellano: "Desesperar", euskara: "Etsi", level: 3},
			{ castellano: "Herencia", euskara: "Herentzia", level: 3},
			{ castellano: "Los del entorno", euskara: "Ingurukoak", level: 3},
			{ castellano: "Puesto de trabajo", euskara: "Lanpostu", level: 3},
			{ castellano: "Apurar(se)", euskara: "Larritu", level: 3},
			{ castellano: "Encantador", euskara: "Maitagarri", level: 3},
			{ castellano: "Amor", euskara: "Maitasun", level: 3},
			{ castellano: "Salud", euskara: "Osasun", level: 3},
			{ castellano: "Curar(se)", euskara: "Sendatu", level: 3},
			{ castellano: "Cuidar(se)", euskara: "Zaindu", level: 3},
			{ castellano: "Feliz", euskara: "Zoriontsu", level: 3},
			{ castellano: "Tacaño", euskara: "Zuhur", level: 3},
			{ castellano: "Conciliar", euskara: "Bateratu", level: 3},
			{ castellano: "Crecer", euskara: "Handitu", level: 3},
			{ castellano: "Enfermar", euskara: "Gaixotu", level: 3},
			{ castellano: "Guardería", euskara: "Haurtzaindegi", level: 3},
			{ castellano: "Vida", euskara: "Bizitza", level: 3},
			{ castellano: "Juventud", euskara: "Gaztaro", level: 3},
			{ castellano: "Infancia", euskara: "Haurtzaro", level: 3},
			{ castellano: "Edad madura", euskara: "Helduaro", level: 3},
			{ castellano: "Ciencias naturales", euskara: "Naturaren zientziak", level: 3},
			{ castellano: "Adolescencia", euskara: "Nerabezaro", level: 3},
			{ castellano: "Vejez", euskara: "Zahartzaro", level: 3},
			{ castellano: "Respirar", euskara: "Arnasa hartu", level: 3},
			{ castellano: "Trasplante de corazón", euskara: "Bihotz-trasplante", level: 3},
			{ castellano: "De pueblo en pueblo", euskara: "Herriz herri", level: 3},
			{ castellano: "Conferencia", euskara: "Hitzaldi", level: 3},
			{ castellano: "Charla", euskara: "Hitzaldi", level: 3},
			{ castellano: "De vez en cuando", euskara: "Noizean behin", level: 3},
			{ castellano: "Donante de órganos", euskara: "Organo-emaile", level: 3},
			{ castellano: "Pastilla", euskara: "Pilula", level: 3},
			{ castellano: "Asociación de trasplantados", euskara: "Trasplantatuen elkalte", level: 3},
			{ castellano: "Afortunadamente", euskara: "Zorionez", level: 3},
			{ castellano: "Patio", euskara: "Ahate", level: 3},
			{ castellano: "Preparar", euskara: "Antolatu", level: 3},
			{ castellano: "Oveja", euskara: "Ardi", level: 3},
			{ castellano: "Casa de campo", euskara: "Landetxe", level: 3},
			{ castellano: "Casa rural", euskara: "Landetxe", level: 3},
			{ castellano: "Gallo", euskara: "Oilar", level: 3},
			{ castellano: "Gallina", euskara: "Oilo", level: 3},
			{ castellano: "Polluelo", euskara: "Txita", level: 3},
			{ castellano: "Conejo", euskara: "Untxi", level: 3},
			{ castellano: "Zarpa", euskara: "Atzapar", level: 3},
			{ castellano: "Garra", euskara: "Atzapar", level: 3},
			{ castellano: "Torpe", euskara: "Baldarra", level: 3},
			{ castellano: "Bigote", euskara: "Bibote", level: 3},
			{ castellano: "Cola, rabo", euskara: "Buztan", level: 3},
			{ castellano: "Zona del cuello", euskara: "Lepoalde", level: 3},
			{ castellano: "Pluma", euskara: "Luma", level: 3},
			{ castellano: "Membrana", euskara: "Mintz", level: 3},
			{ castellano: "Pico", euskara: "Moko", level: 3},
			{ castellano: "Ratón", euskara: "Sagu", level: 3},
			{ castellano: "Tarea", euskara: "Zeregin", level: 3},
			{ castellano: "Sujetador", euskara: "Bularrretako", level: 3},
			{ castellano: "Pantalón", euskara: "Galtza", level: 3},
			{ castellano: "Cinturón", euskara: "Gerriko", level: 3},
			{ castellano: "Piedra", euskara: "Harri", level: 3},
			{ castellano: "Cazadora", euskara: "Jaka", level: 3},
			{ castellano: "Jersey", euskara: "Jertse", level: 3},
			{ castellano: "Bañador", euskara: "Bainujantzi", level: 3},
			{ castellano: "Desnudo", euskara: "Biluzik", level: 3},
			{ castellano: "Tumbona", euskara: "Etzaulki", level: 3},
			{ castellano: "En la arena", euskara: "Hondarretan", level: 3},
			{ castellano: "Orilla del mar", euskara: "Itsasertz", level: 3},
			{ castellano: "Sombrilla", euskara: "Itzalkin", level: 3},
			{ castellano: "Jugar a pala", euskara: "Palan jokatu", level: 3},
			{ castellano: "En el agua", euskara: "Urtan", level: 3},
			{ castellano: "Adivinar", euskara: "Asmatu", level: 3},
			{ castellano: "Fila", euskara: "Ilara", level: 3},
			{ castellano: "Llegar a casa", euskara: "Etxeratu", level: 3},
			{ castellano: "Convencer", euskara: "Konbentzitu", level: 3},
			{ castellano: "Maquillar", euskara: "Makilatu", level: 3},
			{ castellano: "Pintar", euskara: "Margotu", level: 3},
			{ castellano: "Tontería", euskara: "Tontakeria", level: 3},
			{ castellano: "Ombligo", euskara: "Zilbor", level: 3},
			{ castellano: "Centro", euskara: "Erdigune", level: 3},
			{ castellano: "Ciudadano", euskara: "Hiritar", level: 3},
			{ castellano: "Poner en marcha", euskara: "Martxan jarri", level: 3},
			{ castellano: "Romper", euskara: "Puskatu", level: 3},
			{ castellano: "Ocasión excepcional", euskara: "Aukera paregabea", level: 3},
			{ castellano: "Botellón", euskara: "Botila-festa", level: 3},
			{ castellano: "Vaso", euskara: "Edalontzi", level: 3},
			{ castellano: "Derecho", euskara: "Eskubide", level: 3},
			{ castellano: "Que gusta", euskara: "Gustuko", level: 3},
			{ castellano: "Del gusto", euskara: "Gustuko", level: 3},
			{ castellano: "Policía municipal", euskara: "Udaltzain", level: 3},
			{ castellano: "Suciedad", euskara: "Zikinkeria", level: 3},
			{ castellano: "Experto", euskara: "Aditu", level: 3},
			{ castellano: "Al hacer", euskara: "Egitean", level: 3},
			{ castellano: "Atento", euskara: "Erne", level: 3},
			{ castellano: "Comprador", euskara: "Erosle", level: 3},
			{ castellano: "Oferta", euskara: "Ekaintza", level: 3},
			{ castellano: "Ocurrir", euskara: "Gertatu", level: 3},
			{ castellano: "Recomendar", euskara: "Gomendatu", level: 3},
			{ castellano: "Ganga", euskara: "Mauka", level: 3},
			{ castellano: "Acumular", euskara: "Pilatu", level: 3},
			{ castellano: "Duda", euskara: "Zalantza", level: 3},
			{ castellano: "No funcionar", euskara: "Ez ibili", level: 3},
			{ castellano: "Estropearse", euskara: "Hondatu", level: 3},
			{ castellano: "Gratis", euskara: "Musu-truk", level: 3},
			{ castellano: "Mancha", euskara: "Orban", level: 3},
			{ castellano: "Compulsivo", euskara: "Konpultsibo", level: 3},
			{ castellano: "Aficionado a las gangas", euskara: "Maukazale", level: 3},
			{ castellano: "Indeciso", euskara: "Zalantzi", level: 3},
			{ castellano: "Garantía", euskara: "Berme", level: 3},
			{ castellano: "Servicio de atención al cliente", euskara: "Bezeroen arretarako zerbitzu", level: 3},
			{ castellano: "Cosas semejantes", euskara: "Horrelakoak", level: 3},
			{ castellano: "Prestar atención", euskara: "Kasu egin", level: 3},
			{ castellano: "Libro de reclamaciones", euskara: "Kexa liburu", level: 3},
			{ castellano: "Cancelar la cuenta corriente", euskara: "Konte korrontea itxi", level: 3},
			{ castellano: "Antes de nada", euskara: "Lehen-lehenik", level: 3},
			{ castellano: "Denunciar", euskara: "Salatu", level: 3},
			{ castellano: "Tienda", euskara: "Saltoki", level: 3},
			{ castellano: "Comercio", euskara: "Saltoki", level: 3},
			{ castellano: "Tintorería", euskara: "Tindategi", level: 3},
			{ castellano: "Detalladamente", euskara: "Xehe-xehe", level: 3},
			{ castellano: "Sellado", euskara: "Zigilatuta", level: 3},
			{ castellano: "Defecto", euskara: "Akats", level: 3},
			{ castellano: "En una temporada", euskara: "Bolada batean", level: 3},
			{ castellano: "Imprevisto", euskara: "Ezusteko", level: 3},
			{ castellano: "Tipo", euskara: "Mota", level: 3},
			{ castellano: "Componente", euskara: "Osagai", level: 3},
			{ castellano: "Espuma", euskara: "Apar", level: 3},
			{ castellano: "E", euskara: "Bakar", level: 3},
			{ castellano: "Virus informático", euskara: "Birus informátiko", level: 3},
			{ castellano: "Brillante", euskara: "Distiratsu", level: 3},
			{ castellano: "Dentífrico", euskara: "Hortzetako pasta", level: 3},
			{ castellano: "Dentadura", euskara: "Hortz-hagin", level: 3},
			{ castellano: "Refenfuñando", euskara: "Marmarrean", level: 3},
			{ castellano: "Entero", euskara: "Osorik", level: 3},
			{ castellano: "Caries", euskara: "Txantxar", level: 3},
			{ castellano: "Champú", euskara: "Xanpu", level: 3},
			{ castellano: "Feria de artesanía", euskara: "Artisau-azoka", level: 3},
			{ castellano: "Superficie", euskara: "Azalera", level: 3},
			{ castellano: "Promedio de", euskara: "Batez besteko", level: 3},
			{ castellano: "Agencia de viajes", euskara: "Bidaia-agentzia", level: 3},
			{ castellano: "Visita guiada", euskara: "Bisitaldi gidatua", level: 3},
			{ castellano: "Población", euskara: "Biztanleria", level: 3},
			{ castellano: "Tiempo (atmosférico)", euskara: "Eguraldi", level: 3},
			{ castellano: "Humedad", euskara: "Hezetasun", level: 3},
			{ castellano: "Hoja informativa", euskara: "Informazio-orri", level: 3},
			{ castellano: "Comparación", euskara: "Konparazio", level: 3},
			{ castellano: "Espacio natural", euskara: "Natura-gune", level: 3},
			{ castellano: "Parque natural", euskara: "Natura-parke", level: 3},
			{ castellano: "Paisaje", euskara: "Paisai", level: 3},
			{ castellano: "Actividad turística", euskara: "Turismo ekintza", level: 3},
			{ castellano: "Mediante chat", euskara: "Txat bidez", level: 3},
			{ castellano: "Bodega", euskara: "Upategi", level: 3},
			{ castellano: "Habitante", euskara: "Biztanle", level: 3},
			{ castellano: "Observar", euskara: "Erreparatu", level: 3},
			{ castellano: "Por supuesto", euskara: "Jakintzat", level: 3},
			{ castellano: "Conclusión", euskara: "Ondorio", level: 3},
			{ castellano: "Isla", euskara: "Uharte", level: 3},
			{ castellano: "Analizar", euskara: "Aztertu", level: 3},
			{ castellano: "Valioso", euskara: "Aztertu", level: 3},
			{ castellano: "Igual", euskara: "Berdin", level: 3},
			{ castellano: "Decidir", euskara: "Erabaki", level: 3},
			{ castellano: "Electrodoméstico", euskara: "Etxetresna elektriko", level: 3},
			{ castellano: "Utensilio de casa", euskara: "Etxetresna", level: 3},
			{ castellano: "Diferencia", euskara: "Ezberdintasun", level: 3},
			{ castellano: "Caravana", euskara: "Karabana", level: 3},
			{ castellano: "Longitud", euskara: "Luzera", level: 3},
			{ castellano: "Suficiente", euskara: "Nahiko", level: 3},
			{ castellano: "Medida", euskara: "Neurri", level: 3},
			{ castellano: "Litera", euskara: "Ohatze", level: 3},
			{ castellano: "Cama", euskara: "Ohe", level: 3},
			{ castellano: "Pesar", euskara: "Pisatu", level: 3},
			{ castellano: "Peso", euskara: "Pisu", level: 3},
			{ castellano: "Espacio", euskara: "Toki", level: 3},
			{ castellano: "Anchura", euskara: "Zabalera", level: 3},
			{ castellano: "Diferencia", euskara: "Alde", level: 3},
			{ castellano: "Otro", euskara: "Beste", level: 3},
			{ castellano: "Habitual", euskara: "Betiko", level: 3},
			{ castellano: "Rueda", euskara: "Gurpil", level: 3},
			{ castellano: "Placa de  inducción", euskara: "Indukzio-plaka", level: 3},
			{ castellano: "En ningún sitio", euskara: "Inon ez", level: 3},
			{ castellano: "Cremallera", euskara: "Kremailera", level: 3},
			{ castellano: "Olla", euskara: "Lapiko", level: 3},
			{ castellano: "Equivalente", euskara: "Ordezko", level: 3},
			{ castellano: "Altura", euskara: "Altuera", level: 3},
			{ castellano: "Decorar", euskara: "Apaindu", level: 3},
			{ castellano: "Estante", euskara: "Apal", level: 3},
			{ castellano: "En ropa", euskara: "Arropatan", level: 3},
			{ castellano: "Especial", euskara: "Berezi", level: 3},
			{ castellano: "De los/las dos", euskara: "Bietatik", level: 3},
			{ castellano: "Supongamos", euskara: "Demagun", level: 3},
			{ castellano: "Agradecer", euskara: "Eskertu", level: 3},
			{ castellano: "Capricho", euskara: "Gutizia", level: 3},
			{ castellano: "Estropear", euskara: "Hondatu", level: 3},
			{ castellano: "En comida", euskara: "Janaritan", level: 3},
			{ castellano: "Solución", euskara: "Konponbide", level: 3},
			{ castellano: "Consultar", euskara: "Kontsulta egin", level: 3},
			{ castellano: "Profundidad", euskara: "Sakonera", level: 3},
			{ castellano: "Cesto", euskara: "Saski", level: 3},
			{ castellano: "Detalle", euskara: "Zehetasun", level: 3},
			{ castellano: "Colgar", euskara: "Zintzilikatu", level: 3},
			{ castellano: "Dentro de pocos días", euskara: "Egun gutxi barru", level: 4},
			{ castellano: "Pasado mañana", euskara: "Etzi", level: 4},
			{ castellano: "Día siguiente de pasado mañana", euskara: "Etzidamu", level: 4},
			{ castellano: "Al día siguiente", euskara: "Hurrengo egunean", level: 4},
			{ castellano: "Hacia el monte", euskara: "Mendi aldera", level: 4},
			{ castellano: "Partir (ir hacia)", euskara: "Abiatu", level: 4},
			{ castellano: "De nuevo", euskara: "Berriz", level: 4},
			{ castellano: "Otra vez", euskara: "Berriz", level: 4},
			{ castellano: "Aclimatarse", euskara: "Girora moldatu", level: 4},
			{ castellano: "Por lo menos", euskara: "Gutxienez", level: 4},
			{ castellano: "Como mínimo", euskara: "Gutxienez", level: 4},
			{ castellano: "Esperar", euskara: "Itxaron", level: 4},
			{ castellano: "Análisis de sangre", euskara: "Odol-analisi", level: 4},
			{ castellano: "Anoche", euskara: "Bart", level: 4},
			{ castellano: "De nuevo", euskara: "Berriro", level: 4},
			{ castellano: "Vomitar", euskara: "Botaka egin", level: 4},
			{ castellano: "Parte meteorológico", euskara: "Eguraldi iragarpen", level: 4},
			{ castellano: "Juntos", euskara: "Elkarrekin", level: 4},
			{ castellano: "Alud", euskara: "Elur-jausi", level: 4},
			{ castellano: "Avalancha", euskara: "Elur-jausi", level: 4},
			{ castellano: "Mejorar", euskara: "Hobera egin", level: 4},
			{ castellano: "Fuerte", euskara: "Indartsu", level: 4},
			{ castellano: "Tienda de campaña", euskara: "Kanpin-denda", level: 4},
			{ castellano: "Intentar", euskara: "Saiatu", level: 4},
			{ castellano: "Mareo", euskara: "Zorabio", level: 4},
			{ castellano: "Enseguida", euskara: "Berehala", level: 4},
			{ castellano: "Compañero de expedición", euskara: "Ezpedizioko kide", level: 4},
			{ castellano: "Hacer saber", euskara: "Jakinarazi", level: 4},
			{ castellano: "Seguir adelante", euskara: "Aurrera egin", level: 4},
			{ castellano: "Cima", euskara: "Gailur", level: 4},
			{ castellano: "Oscurecer", euskara: "Ilundu", level: 4},
			{ castellano: "Electricidad", euskara: "Argindar", level: 4},
			{ castellano: "Adaptado para minusválidos", euskara: "Elbarrituentzat egokitua", level: 4},
			{ castellano: "Lavadero", euskara: "Garbileku", level: 4},
			{ castellano: "Lavandería", euskara: "Garbileku", level: 4},
			{ castellano: "Parque infantil", euskara: "Haur-parke", level: 4},
			{ castellano: "Cine al aire libre", euskara: "Kanpoko zinema", level: 4},
			{ castellano: "Pista de deporte", euskara: "Kiroletako pista", level: 4},
			{ castellano: "Tarjeta de crédito", euskara: "Kreditu txartel", level: 4},
			{ castellano: "Mientras", euskara: "Bitartean", level: 4},
			{ castellano: "Tía", euskara: "Izeko", level: 4},
			{ castellano: "Morcilla", euskara: "Odolki", level: 4},
			{ castellano: "Proponer", euskara: "Proposatu", level: 4},
			{ castellano: "Pista de deporte", euskara: "Kirol-pista", level: 4},
			{ castellano: "Tiempo después de la cena (sobremesa)", euskara: "Afalondo", level: 4},
			{ castellano: "Vete a saber", euskara: "Auskalo", level: 4},
			{ castellano: "Por lo tanto", euskara: "Beraz", level: 4},
			{ castellano: "Berezi", euskara: "Especial", level: 4},
			{ castellano: "Despedida de soltero", euskara: "ezkondu aurreko agur festa", level: 4},
			{ castellano: "Falso", euskara: "Faltsu", level: 4},
			{ castellano: "Fiesta", euskara: "Festa", level: 4},
			{ castellano: "Invitar", euskara: "Gonbidatu", level: 4},
			{ castellano: "Además", euskara: "Gainera", level: 4},
			{ castellano: "En busca de ideas", euskara: "Ideien bila", level: 4},
			{ castellano: "Disfrazado", euskara: "Mozorratu", level: 4},
			{ castellano: "Disfraz", euskara: "Mozoeeo", level: 4},
			{ castellano: "Broma", euskara: "Txantxa", level: 4},
			{ castellano: "Cuidar", euskara: "Zaindu", level: 4},
			{ castellano: "Novia", euskara: "Emaztegai", level: 4},
			{ castellano: "Efraile", euskara: "Fraide", level: 4},
			{ castellano: "Enorme", euskara: "Galanta", level: 4},
			{ castellano: "Tremendo", euskara: "Galanta", level: 4},
			{ castellano: "Susto tremendo", euskara: "Susto galanta", level: 4},
			{ castellano: "Rampa", euskara: "Arrapala", level: 4},
			{ castellano: "Que no ", euskara: "Ezetz", level: 4},
			{ castellano: "Silla de ruedas", euskara: "Gurpil-aulki", level: 4},
			{ castellano: "Volver", euskara: "Itzuli", level: 4},
			{ castellano: "Bacalao", euskara: "Bakailao", level: 4},
			{ castellano: "Cabezudo", euskara: "Buruhandi", level: 4},
			{ castellano: "Gigante", euskara: "Erraldoi", level: 4},
			{ castellano: "Romería", euskara: "Erromeria", level: 4},
			{ castellano: "Deporte rural", euskara: "Herri-kirol", level: 4},
			{ castellano: "Programa de fiestas", euskara: "Jai-egutarau", level: 4},
			{ castellano: "Pasacalle", euskara: "Kalejira", level: 4},
			{ castellano: "Reparto de premios", euskara: "Sari banaketa", level: 4},
			{ castellano: "Tiempo disponible", euskara: "Asti", level: 4},
			{ castellano: "Confirmar", euskara: "Berretsi", level: 4},
			{ castellano: "Cuanto antes", euskara: "Lehenbailehen", level: 4},
			{ castellano: "Participar", euskara: "Parte hartu", level: 4},
			{ castellano: "Parque de aventura", euskara: "Abentura-parke", level: 4},
			{ castellano: "Mayor de", euskara: "Aurrerako", level: 4},
			{ castellano: "En adelante", euskara: "Aurrerako", level: 4},
			{ castellano: "Ofrecer", euskara: "Eskaini", level: 4},
			{ castellano: "Cuestionario", euskara: "Galdera-sorta", level: 4},
			{ castellano: "Recorrido", euskara: "Ibilbide", level: 4},
			{ castellano: "Escuela", euskara: "Ikastetxe", level: 4},
			{ castellano: "Colegio", euskara: "Ikastetxe", level: 4},
			{ castellano: "Ocasión de hacer", euskara: "Egiteko aukera", level: 4},
			{ castellano: "Totalmente", euskara: "Erabat", level: 4},
			{ castellano: "Ocasión de disfrutar", euskara: "Gozatzeko aukera", level: 4},
			{ castellano: "Digno de ser visto", euskara: "Ikusgarri", level: 4},
			{ castellano: "Espectacular", euskara: "Ikusgarri", level: 4},
			{ castellano: "Tremendo", euskara: "Izugarrizko", level: 4},
			{ castellano: "Enorme", euskara: "Izugarrizko", level: 4},
			{ castellano: "Habitual", euskara: "Ohiko", level: 4},
			{ castellano: "Corriente", euskara: "Ohiko", level: 4},
			{ castellano: "Encontrarse", euskara: "Topatu", level: 4},
			{ castellano: "Gastar", euskara: "Xahutu", level: 4},
			{ castellano: "Despilfarrar", euskara: "Xahutu", level: 4},
			{ castellano: "Director de coro", euskara: "Abesbatza-zuzendari", level: 4},
			{ castellano: "Tiempo libre", euskara: "Aisialdi", level: 4},
			{ castellano: "Ridículo", euskara: "Barregarri", level: 4},
			{ castellano: "Monedero", euskara: "Diru-zorro", level: 4},
			{ castellano: "Proyecto", euskara: "Egitasmo", level: 4},
			{ castellano: "Plan", euskara: "Egitasmo", level: 4},
			{ castellano: "Resultado", euskara: "Emaitza", level: 4},
			{ castellano: "Actuación", euskara: "Emanaldi", level: 4},
			{ castellano: "Ensayar", euskara: "Entseatu", level: 4},
			{ castellano: "Ensayo", euskara: "Entsegu", level: 4},
			{ castellano: "Trabajo manual", euskara: "Eskulan", level: 4},
			{ castellano: "Entonar", euskara: "Intonatu", level: 4},
			{ castellano: "Participante", euskara: "Parte-hartzaile", level: 4},
			{ castellano: "Hacer punto", euskara: "Puntu egin", level: 4},
			{ castellano: "Fortalecer", euskara: "Sendotu", level: 4},
			{ castellano: "Revista", euskara: "Aldizkari", level: 4},
			{ castellano: "Lugar de residencia", euskara: "Bizitoki", level: 4},
			{ castellano: "Bedida", euskara: "Edari", level: 4},
			{ castellano: "Enfermo", euskara: "Gaixo", level: 4},
			{ castellano: "Caramelo", euskara: "Gozoki", level: 4},
			{ castellano: "Cuidar", euskara: "Sendatu", level: 4},
			{ castellano: "Herida", euskara: "Zauri", level: 4},
			{ castellano: "Herido", euskara: "Zauritu", level: 4},
			{ castellano: "Documento", euskara: "Agiri", level: 4},
			{ castellano: "Recién llegado", euskara: "Etorri-berri", level: 4},
			{ castellano: "Aterrado", euskara: "Beldurtuta", level: 4},
			{ castellano: "Temblando", euskara: "Dardaka", level: 4},
			{ castellano: "Volando", euskara: "Hegan", level: 4},
			{ castellano: "Volar", euskara: "Hegan egin", level: 4},
			{ castellano: "Terrible", euskara: "Ikaragarri", level: 4},
			{ castellano: "Paracaídas", euskara: "Paraxut", level: 4},
			{ castellano: "Marear(se)", euskara: "Zorabiatu", level: 4},

		];

		function getDictionaryByInitial (level, initial, inputLang, outputLang) {
			var itzulpenakSubset = itzulpenak
				.filter(function (elem) {
					return elem[inputLang][0].toUpperCase() === initial && (!level || elem.level === level);
				});
			var wordIndex = [];
			var itzulpenakOutput = [];
			itzulpenakSubset.forEach(function (elem) {
				if (wordIndex.indexOf(elem[inputLang]) < 0) {
					wordIndex.push(elem[inputLang]);
					itzulpenakOutput.push({ 
						word: elem[inputLang], 
						translation: elem[outputLang]
					});
				} else {
					for (var i = 0; i < itzulpenakOutput.length; i++) {
						if(itzulpenakOutput[i].word === elem[inputLang]) {
							var translations = itzulpenakOutput[i].translation.split(', ');
							if (translations.indexOf(elem[outputLang]) < 0) {
								translations.push(elem[outputLang]);
								itzulpenakOutput[i].translation = translations.join(', ');
							}
							break;
						}
					}
				}
			});
			return itzulpenakOutput;
		}

		return {
			getEuskara: function(level, initial) {
				return getDictionaryByInitial(level, initial, 'euskara', 'castellano');
			},

			getCastellano: function(level, initial) {
				return getDictionaryByInitial(level, initial, 'castellano', 'euskara');
			},

			getAll: function () {
				return itzulpenak;
			}
		}
	};

	ItzulpenFactory.$inject = [];

	angular.module('moteApp')
		.factory('itzulpenFactory', ItzulpenFactory);
})();